---
name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-yaml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate YAML files
        run: |
          find . -name '*.yml' -o -name '*.yaml' | xargs -I {} yamllint -c .yamllint {}

  lint-trailing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check for trailing whitespace
        run: |
          if grep -rI --include '*.groovy' --include '*.yml' '[[:space:]]$' ./; then
            echo "Trailing whitespace found!"
            exit 1
          else
            echo "No trailing whitespace."
          fi

  lint-helm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v4.0.4

      - name: Lint all Helm charts
        run: |
          # Find all chart directories
          for chart in $(find ./charts -maxdepth 1 -mindepth 1 -type d); do
            echo "Linting chart: $chart"
            helm lint "$chart" --strict
          done

      - name: Template Helm charts (dry-run)
        run: |
          for chart in $(find ./charts -maxdepth 1 -mindepth 1 -type d); do
            echo "Rendering templates for chart: $chart"
            helm template "$chart" --debug --values "$chart/values.yaml"
          done
